version: '3.9'

services:
  web-scraper-api:
    build: ./api
    container_name: web-scraper-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
